[package]
name = "bincode-benchmark"
version = "0.1.0"
authors = ["Joel Dice <joel.dice@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1"
serde = "1"
serde_derive = "1"
serde_bytes = "0.11"
uuid = { version = "0.7", features = ["serde", "v4"] }

[profile.release]
debug = true
